columns = [
 'company',
 'symbol',
 'Open',
 'High',
 'Low',
 'Close',
 'Adj Close',
 'Volume',
 'Dividends',
 'Stock Splits',
 'Companhia',
 'Trimestre',
 '00.01 - Ações Ordinárias - Composição do Capital',
 '00.01.01 - Ações Ordinárias em Tesouraria - Composição do Capital',
 '00.01.02 - Ações Ordinárias Outras - Composição do Capital',
 '00.02 - Ações Preferenciais - Composição do Capital',
 '00.02.01 - Ações Prerenciais em Tesouraria - Composição do Capital',
 '00.02.02 - Ações Prerenciais Outras - Composição do Capital',
 '01 - Ativo Total - Balanço Patrimonial Ativo',
 '01.01 - Ativo Circulante de Curto Prazo - Balanço Patrimonial Ativo',
 '01.01.01 - Caixa e Disponibilidades de Caixa - Balanço Patrimonial Ativo',
 '01.01.02 - Aplicações Financeiras - Balanço Patrimonial Ativo',
 '01.01.03 - Contas a Receber - Balanço Patrimonial Ativo',
 '01.01.04 - Estoques - Balanço Patrimonial Ativo',
 '01.01.05 - Ativos Biológicos - Balanço Patrimonial Ativo',
 '01.01.06 - Tributos - Balanço Patrimonial Ativo',
 '01.01.07 - Despesas - Balanço Patrimonial Ativo',
 '01.01.09 - Outros Ativos Circulantes - Balanço Patrimonial Ativo',
 '01.02 - Ativo Não Circulante de Longo Prazo - Balanço Patrimonial Ativo',
 '01.02.01 - Ativos Financeiros - Balanço Patrimonial Ativo',
 '01.02.01.01 - Ativos Financeiros a Valor Justo - Balanço Patrimonial Ativo',
 '01.02.01.02 - Ativos Financeiros ao Custo Amortizado - Balanço Patrimonial Ativo',
 '01.02.01.03 - Contas a Receber - Balanço Patrimonial Ativo',
 '01.02.01.04 - Estoques - Balanço Patrimonial Ativo',
 '01.02.01.05 - Ativos Biológicos - Balanço Patrimonial Ativo',
 '01.02.01.06 - Tributos - Balanço Patrimonial Ativo',
 '01.02.01.07 - Despesas - Balanço Patrimonial Ativo',
 '01.02.01.09 - Outros Ativos Não Circulantes - Balanço Patrimonial Ativo',
 '01.02.02 - Investimentos Não Capex - Balanço Patrimonial Ativo',
 '01.02.02.01 - Propriedades - Balanço Patrimonial Ativo',
 '01.02.02.02 - Arrendamentos - Balanço Patrimonial Ativo',
 '01.02.03 - Imobilizados - Balanço Patrimonial Ativo',
 '01.02.03.01 - Imobilizados em Operação - Balanço Patrimonial Ativo',
 '01.02.03.02 - Imobilizados em Arrendamento - Balanço Patrimonial Ativo',
 '01.02.03.03 - Imobilizados em Andamento - Balanço Patrimonial Ativo',
 '01.02.04 - Intangível - Balanço Patrimonial Ativo',
 '01.03 - Empréstimos - Balanço Patrimonial Ativo',
 '01.04 - Tributos Diferidos - Balanço Patrimonial Ativo',
 '01.05 - Investimentos - Balanço Patrimonial Ativo',
 '01.05.01 - Participações em Coligadas - Balanço Patrimonial Ativo',
 '01.05.02 - Participações em Controladas - Balanço Patrimonial Ativo',
 '01.06 - Imobilizados - Balanço Patrimonial Ativo',
 '01.06.01 - Propriedades - Balanço Patrimonial Ativo',
 '01.06.02 - Arrendamento - Balanço Patrimonial Ativo',
 '01.06.03 - Tangíveis - Balanço Patrimonial Ativo',
 '01.07 - Intangíveis - Balanço Patrimonial Ativo',
 '01.07.01 - Intangíveis - Balanço Patrimonial Ativo',
 '01.07.02 - Goodwill - Balanço Patrimonial Ativo',
 '01.08 - Permanente - Balanço Patrimonial Ativo',
 '01.09.09 - Outros Ativos - Balanço Patrimonial Ativo',
 '02 - Passivo Total - Balanço Patrimonial Passivo',
 '02.01 - Passivo Circulante de Curto Prazo - Balanço Patrimonial Passivo',
 '02.01.01 - Obrigações Sociais e Trabalhistas - Balanço Patrimonial Passivo',
 '02.01.01.01 - Obrigações Sociais - Balanço Patrimonial Passivo',
 '02.01.01.02 - Obrigações Trabalhistas - Balanço Patrimonial Passivo',
 '02.01.01.09 - Outras Obrigações - Balanço Patrimonial Passivo',
 '02.01.02 - Fornecedores - Balanço Patrimonial Passivo',
 '02.01.02.01 - Fornecedores Nacionais - Balanço Patrimonial Passivo',
 '02.01.02.02 - Fornecedores Estrangeiros - Balanço Patrimonial Passivo',
 '02.01.03 - Obrigações Fiscais - Balanço Patrimonial Passivo',
 '02.01.03.01 - Obrigações Fiscais Federais - Balanço Patrimonial Passivo',
 '02.01.03.02 - Obrigações Fiscais Estaduais - Balanço Patrimonial Passivo',
 '02.01.03.03 - Obrigações Fiscais Municipais - Balanço Patrimonial Passivo',
 '02.01.03.09 - Outras Obrigações Fiscais - Balanço Patrimonial Passivo',
 '02.01.04 - Empréstimos, Financiamentos e Debêntures - Balanço Patrimonial Passivo',
 '02.01.04.01 - Empréstimos e Financiamentos - Balanço Patrimonial Passivo',
 '02.01.04.01.01 - Empréstimos e Financiamentos em Moeda Nacional - Balanço Patrimonial Passivo',
 '02.01.04.01.02 - Empréstimos e Financiamentos em Moeda Estrangeira - Balanço Patrimonial Passivo',
 '02.01.04.02 - Debêntures - Balanço Patrimonial Passivo',
 '02.01.04.03 - Arrendamentos - Balanço Patrimonial Passivo',
 '02.01.04.09 - Outros empréstimos, financiamentos e debêntures - Balanço Patrimonial Passivo',
 '02.01.05 - Outras Obrigações - Balanço Patrimonial Passivo',
 '02.01.05.01 - Passivos com Partes Relacionadas - Balanço Patrimonial Passivo',
 '02.01.05.09 - Outros - Balanço Patrimonial Passivo',
 '02.01.06 - Provisões - Balanço Patrimonial Passivo',
 '02.01.06.01 - Provisões Específicas - Balanço Patrimonial Passivo',
 '02.01.06.01.01 - Provisões Fiscais - Balanço Patrimonial Passivo',
 '02.01.06.01.02 - Provisões Trabalhistas e Previdenciárias - Balanço Patrimonial Passivo',
 '02.01.06.01.03 - Provisões para Benefícios a Empregados - Balanço Patrimonial Passivo',
 '02.01.06.01.04 - Provisões Judiciais Cíveis - Balanço Patrimonial Passivo',
 '02.01.06.01.05 - Outras Provisões Específicas - Balanço Patrimonial Passivo',
 '02.01.06.02 - Provisões Outras - Balanço Patrimonial Passivo',
 '02.01.06.02.01 - Provisões para Garantias - Balanço Patrimonial Passivo',
 '02.01.06.02.02 - Provisões para Reestruturação - Balanço Patrimonial Passivo',
 '02.01.06.02.03 - Provisões para Passivos Ambientais e de Desativação - Balanço Patrimonial Passivo',
 '02.01.07 - Passivos sobre Ativos Não-Correntes a Venda e Descontinuados - Balanço Patrimonial Passivo',
 '02.01.07.01 - Passivos sobre Ativos Não-Correntes a Venda - Balanço Patrimonial Passivo',
 '02.01.07.02 - Passivos sobre Ativos de Operações Descontinuadas - Balanço Patrimonial Passivo',
 '02.01.09 - Outros Passivos - Balanço Patrimonial Passivo',
 '02.02 - Passivo Não Circulante de Longo Prazo - Balanço Patrimonial Passivo',
 '02.02.01 - Empréstimos e Financiamentos de Longo Prazo - Balanço Patrimonial Passivo',
 '02.02.01.01 - Empréstimos e Financiamentos - Balanço Patrimonial Passivo',
 '02.02.01.01.01 - Empréstimos e Financiamentos em Moeda Nacional - Balanço Patrimonial Passivo',
 '02.02.01.01.02 - Empréstimos e Financiamentos em Moeda Estrangeira - Balanço Patrimonial Passivo',
 '02.02.01.02 - Debêntures - Balanço Patrimonial Passivo',
 '02.02.01.03 - Arrendamentos - Balanço Patrimonial Passivo',
 '02.02.02 - Outras Obrigações - Balanço Patrimonial Passivo',
 '02.02.02.01 - Com Partes Relacionadas - Balanço Patrimonial Passivo',
 '02.02.02.02 - Outras Obrigações - Balanço Patrimonial Passivo',
 '02.02.02.09 - Outros empréstimos, financiamentos e debêntures - Balanço Patrimonial Passivo',
 '02.02.03 - Tributos Diferidos - Balanço Patrimonial Passivo',
 '02.02.03.01 - Imposto de Renda e Contribuição Social - Balanço Patrimonial Passivo',
 '02.02.03.02 - Outros tributos diferidos - Balanço Patrimonial Passivo',
 '02.02.04 - Provisões - Balanço Patrimonial Passivo',
 '02.02.04.01 - Provisões Específicas - Balanço Patrimonial Passivo',
 '02.02.04.01.01 - Provisões Fiscais - Balanço Patrimonial Passivo',
 '02.02.04.01.02 - Provisões Trabalhistas e Previdenciárias - Balanço Patrimonial Passivo',
 '02.02.04.01.03 - Provisões para Benefícios a Empregados - Balanço Patrimonial Passivo',
 '02.02.04.01.04 - Provisões Judiciais Cíveis - Balanço Patrimonial Passivo',
 '02.02.04.02 - Outras Provisões - Balanço Patrimonial Passivo',
 '02.02.04.02.01 - Provisões para Garantias - Balanço Patrimonial Passivo',
 '02.02.04.02.02 - Provisões para Reestruturação - Balanço Patrimonial Passivo',
 '02.02.04.02.03 - Provisões para Passivos Ambientais e de Desativação - Balanço Patrimonial Passivo',
 '02.02.05 - Passivos sobre Ativos Não-Correntes a Venda e Descontinuados - Balanço Patrimonial Passivo',
 '02.02.05.01 - Passivos sobre Ativos Não-Correntes a Venda - Balanço Patrimonial Passivo',
 '02.02.05.02 - Passivos sobre Ativos de Operações Descontinuadas - Balanço Patrimonial Passivo',
 '02.02.06 - Lucros e Receitas a Apropriar - Balanço Patrimonial Passivo',
 '02.02.06.01 - Lucros a Apropriar - Balanço Patrimonial Passivo',
 '02.02.06.02 - Receitas a Apropriar - Balanço Patrimonial Passivo',
 '02.02.06.03 - Subvenções de Investimento a Apropriar - Balanço Patrimonial Passivo',
 '02.02.09 - Outros Passivos - Balanço Patrimonial Passivo',
 '02.03 - Patrimônio Líquido - Balanço Patrimonial Passivo',
 '02.03.01 - Capital Social - Balanço Patrimonial Passivo',
 '02.03.02 - Reservas de Capital - Balanço Patrimonial Passivo',
 '02.03.03 - Reservas de Reavaliação - Balanço Patrimonial Passivo',
 '02.03.04 - Reservas de Lucros - Balanço Patrimonial Passivo',
 '02.03.05 - Lucros ou Prejuízos Acumulados - Balanço Patrimonial Passivo',
 '02.03.06 - Ajustes de Avaliação Patrimonial - Balanço Patrimonial Passivo',
 '02.03.07 - Ajustes Acumulados de Conversão - Balanço Patrimonial Passivo',
 '02.03.08 - Outros Resultados Abrangentes - Balanço Patrimonial Passivo',
 '02.04 - Outros Passivos ou Provissões - Balanço Patrimonial Passivo',
 '03.01 - Receita Bruta - Demonstração do Resultado',
 '03.02 - Custo de Produção - Demonstração do Resultado',
 '03.03 - Resultado Bruto (Receita Líquida) - Demonstração do Resultado',
 '03.04 - Despesas Operacionais - Demonstração do Resultado',
 '03.04.01 - Despesas com Vendas - Demonstração do Resultado',
 '03.04.02 - Despesas Gerais e Administrativas - Demonstração do Resultado',
 '03.04.09 - Outras despesas, receitas ou equivalências - Demonstração do Resultado',
 '03.05 - LAJIR EBIT Resultado Antes do Resultado Financeiro e dos Tributos - Demonstração do Resultado',
 '03.06 - Resultado Financeiro (Não Operacional) - Demonstração do Resultado',
 '03.07 - Resultado Antes dos Tributos sobre o Lucro - Demonstração do Resultado',
 '03.08 - Impostos IRPJ e CSLL - Demonstração do Resultado',
 '03.09 - Resultado Líquido das Operações Continuadas - Demonstração do Resultado',
 '03.10 - Resultado Líquido das Operações Descontinuadas - Demonstração do Resultado',
 '03.11 - Lucro Líquido - Demonstração do Resultado',
 '06.01 - Caixa das Operações - Demonstração de Fluxo de Caixa',
 '06.01.01 - Caixa das Operações - Demonstração de Fluxo de Caixa',
 '06.01.02 - Variações de Ativos e Passivos - Demonstração de Fluxo de Caixa',
 '06.01.09 - Outros Caixas Operacionais - Demonstração de Fluxo de Caixa',
 '06.02 - Caixa de Investimentos CAPEX - Demonstração de Fluxo de Caixa',
 '06.02.01 - Investimentos - Demonstração de Fluxo de Caixa',
 '06.02.02 - Imobilizado e Intangível - Demonstração de Fluxo de Caixa',
 '06.02.03 - Aplicações Financeiras - Demonstração de Fluxo de Caixa',
 '06.02.04 - Coligadas e Controladas - Demonstração de Fluxo de Caixa',
 '06.02.05 - Juros sobre Capital Próprio e Dividendos - Demonstração de Fluxo de Caixa',
 '06.02.09 - Outros Caixas de Investimento - Demonstração de Fluxo de Caixa',
 '06.03 - Caixa de Financiamento - Demonstração de Fluxo de Caixa',
 '06.03.01 - Capital - Demonstração de Fluxo de Caixa',
 '06.03.02 - Ações e Acionistas - Demonstração de Fluxo de Caixa',
 '06.03.03 - Debêntures, empréstimos e financiamentos - Demonstração de Fluxo de Caixa',
 '06.03.04 - Credores - Demonstração de Fluxo de Caixa',
 '06.03.05 - Captações e Amortizações - Demonstração de Fluxo de Caixa',
 '06.03.06 - Juros JCP e Dividendos - Demonstração de Fluxo de Caixa',
 '06.03.09 - Outros Caixas de Financiamento - Demonstração de Fluxo de Caixa',
 '06.04 - Caixa da Variação Cambial - Demonstração de Fluxo de Caixa',
 '06.05 - Variação do Caixa - Demonstração de Fluxo de Caixa',
 '06.05.01 - Saldo Inicial do Caixa  - Demonstração de Fluxo de Caixa',
 '06.05.02 - Saldo Final do Caixa - Demonstração de Fluxo de Caixa',
 '07.01 - Receitas - Demonstração de Valor Adiconado',
 '07.01.01 - Vendas - Demonstração de Valor Adiconado',
 '07.01.02 - Outras Receitas - Demonstração de Valor Adiconado',
 '07.01.03 - Ativos Próprios - Demonstração de Valor Adiconado',
 '07.01.04 - Reversão de Créditos Podres - Demonstração de Valor Adiconado',
 '07.02 - Custos dos Insumos - Demonstração de Valor Adiconado',
 '07.02.01 - Custo de Mercadorias - Demonstração de Valor Adiconado',
 '07.02.02 - Custo de Materiais, Energia e Terceiros - Demonstração de Valor Adiconado',
 '07.02.03 - Valores Ativos - Demonstração de Valor Adiconado',
 '07.02.04 - Outros - Demonstração de Valor Adiconado',
 '07.03 - Valor Adicionado Bruto - Demonstração de Valor Adiconado',
 '07.04 - Retenções - Demonstração de Valor Adiconado',
 '07.04.01 - Depreciação e Amortização - Demonstração de Valor Adiconado',
 '07.04.02 - Outras retenções - Demonstração de Valor Adiconado',
 '07.05 - Valor Adicionado Líquido - Demonstração de Valor Adiconado',
 '07.06 - Valor Adicionado em Transferência - Demonstração de Valor Adiconado',
 '07.06.01 - Resultado de Equivalência Patrimonial - Demonstração de Valor Adiconado',
 '07.06.02 - Receitas Financeiras - Demonstração de Valor Adiconado',
 '07.06.03 - Outros - Demonstração de Valor Adiconado',
 '07.07 - Valor Adicionado Total a Distribuir - Demonstração de Valor Adiconado',
 '07.08 - Distribuição do Valor Adicionado - Demonstração de Valor Adiconado',
 '07.08.01 - Pessoal - Demonstração de Valor Adiconado',
 '07.08.01.01 - Remuneração Direta - Demonstração de Valor Adiconado',
 '07.08.01.02 - Benefícios - Demonstração de Valor Adiconado',
 '07.08.01.03 - FGTS - Demonstração de Valor Adiconado',
 '07.08.01.04 - Outros - Demonstração de Valor Adiconado',
 '07.08.02 - Impostos, Taxas e Contribuições - Demonstração de Valor Adiconado',
 '07.08.02.01 - Federais - Demonstração de Valor Adiconado',
 '07.08.02.02 - Estaduais - Demonstração de Valor Adiconado',
 '07.08.02.03 - Municipais - Demonstração de Valor Adiconado',
 '07.08.03 - Remuneração de Capital de Terceiros - Demonstração de Valor Adiconado',
 '07.08.03.01 - Juros Pagos - Demonstração de Valor Adiconado',
 '07.08.03.02 - Aluguéis - Demonstração de Valor Adiconado',
 '07.08.04 - Remuneração de Capital Próprio - Demonstração de Valor Adiconado',
 '07.08.04.01 - Juros sobre o Capital Próprio - Demonstração de Valor Adiconado',
 '07.08.04.02 - Dividendos - Demonstração de Valor Adiconado',
 '07.08.04.03 - Lucros Retidos - Demonstração de Valor Adiconado',
 '07.08.05 - Outros - Demonstração de Valor Adiconado',
 '11.01.01 - Capital de Giro (Ativos Circulantes - Passivos Circulantes) - Relações entre Ativos e Passivos',
 '11.01.02 - Liquidez (Ativos Circulantes por Passivos Circulantes) - Relações entre Ativos e Passivos',
 '11.01.03 - Ativos Circulantes de Curto Prazo por Ativos - Relações entre Ativos e Passivos',
 '11.01.04 - Ativos Não Circulantes de Longo Prazo por Ativos - Relações entre Ativos e Passivos',
 '11.02 - Passivos por Ativos - Relações entre Ativos e Passivos',
 '11.02.01 - Passivos Circulantes de Curto Prazo por Ativos - Relações entre Ativos e Passivos',
 '11.02.02 - Passivos Não Circulantes de Longo Prazo por Ativos - Relações entre Ativos e Passivos',
 '11.02.03 - Passivos Circulantes de Curto Prazo por Passivos - Relações entre Ativos e Passivos',
 '11.02.04 - Passivos Não Circulantes de Longo Prazo por Passivos - Relações entre Ativos e Passivos',
 '11.03 - Patrimônio Líquido por Ativos - Relações entre Ativos e Passivos',
 '11.03.01 - Equity Multiplier (Ativos por Patrimônio Líquido) - Relações entre Ativos e Passivos',
 '11.03.02 - Passivos por Patrimônio Líquido - Relações entre Ativos e Passivos',
 '11.03.02.01 - Passivos Circulantes de Curto Prazo por Patrimônio Líquido - Relações entre Ativos e Passivos',
 '11.03.02.02 - Passivos Não Circulantes de Longo Prazo por Patrimônio Líquido - Relações entre Ativos e Passivos',
 '11.04 - Capital Social por Patrimônio Líquido - Patrimônio',
 '11.05 - Reservas por Patrimônio Líquido - Patrimônio',
 '12.01 - Dívida Bruta - Dívida',
 '12.01.01 - Dívida Bruta Circulante de Curto Prazo - Dívida',
 '12.01.02 - Dívida Bruta Não Circulante de Longo Prazo - Dívida',
 '12.01.03 - Dívida Bruta Circulante de Curto Prazo por Dívida Bruta - Dívida',
 '12.01.04 - Dívida Bruta Não Circulante de Longo Prazo por Dívida Bruta - Dívida',
 '12.01.05 - Dívida Bruta em Moeda Nacional - Dívida',
 '12.01.06 - Dívida Bruta em Moeda Estrangeira - Dívida',
 '12.01.07 - Dívida Bruta em Moeda Nacional por Dívida Bruta - Dívida',
 '12.01.08 - Dívida Bruta em Moeda Estrangeira por Dívdida Bruta - Dívida',
 '12.02.01 - Dívida Bruta por Patrimônio Líquido - Dívida',
 '12.02.02 - Endividamento Financeiro - Dívida',
 '12.03 - Patrimônio Imobilizado em Capex, Investimentos Não Capex e Intangível Não Capex - Dívida',
 '12.03.01 - Patrimônio Imobilizado por Patrimônio Líquido - Dívida',
 '12.04 - Dívida Líquida - Dívida',
 '12.04.01 - Dívida Líquida por EBITDA - Dívida',
 '12.04.01 - Serviço da Dívida (Dívida Líquida por Resultado) - Dívida',
 '13.03 - Contas a Receber por Faturamento - Resultados Fundamentalistas',
 '13.03.01 - Contas a Receber Não Circulantes de Curto Prazo por Faturamento - Resultados Fundamentalistas',
 '13.03.02 - Contas a Receber Circulantes de Longo Prazo por Faturamento - Resultados Fundamentalistas',
 '13.04 - Estoques por Faturamento - Resultados Fundamentalistas',
 '13.04.01 - Estoques Não Circulantes de Curto Prazo por Faturamento - Resultados Fundamentalistas',
 '13.04.02 - Estoques Circulantes de Longo Prazo por Faturamento - Resultados Fundamentalistas',
 '13.05 - Ativos Biológicos por Faturamento - Resultados Fundamentalistas',
 '13.05.01 - Ativos Biológicos Não Circulantes de Curto Prazo por Faturamento - Resultados Fundamentalistas',
 '13.05.02 - Ativos Biológicos Circulantes de Longo Prazo por Faturamento - Resultados Fundamentalistas',
 '13.06 - Tributos por Faturamento - Resultados Fundamentalistas',
 '13.06.01 - Tributos Não Circulantes de Curto Prazo por Faturamento - Resultados Fundamentalistas',
 '13.06.02 - Tributos Circulantes de Longo Prazo por Faturamento - Resultados Fundamentalistas',
 '13.07 - Despesas por Faturamento - Resultados Fundamentalistas',
 '13.07.01 - Despesas Não Circulantes de Curto Prazo por Faturamento - Resultados Fundamentalistas',
 '13.07.02 - Despesas Circulantes de Longo Prazo por Faturamento - Resultados Fundamentalistas',
 '13.09 - Outros Ativos por Faturamento - Resultados Fundamentalistas',
 '13.09.01 - Outros Ativos Não Circulantes de Curto Prazo por Faturamento - Resultados Fundamentalistas',
 '13.09.02 - Outros Ativos Não Circulantes de Longo Prazo por Faturamento - Resultados Fundamentalistas',
 '14.01.01 - Receita por Ativos - Resultados Fundamentalistas',
 '14.01.02 - Receita por Patrimônio - Resultados Fundamentalistas',
 '14.02.01 - Coeficiente de Retorno (Resultado por Ativos) - Resultados Fundamentalistas',
 '14.02.02 - ROE (Resultado por Patrimônio) - Resultados Fundamentalistas',
 '14.03 - Capital Investido - Resultados Fundamentalistas',
 '14.03.01 - ROIC (Retorno por Capital Investido) - Resultados Fundamentalistas',
 '14.04.01 - ROAS (EBIT por Ativos) - Resultados Fundamentalistas',
 '15.01 - Remuneração de Capital - Resultados Fundamentalistas',
 '15.01.01 - Remuneração de Capital de Terceiros por Remuneração de Capital - Resultados Fundamentalistas',
 '15.01.01.01 - Juros Pagos por Remuneração de Capital de Terceiros - Resultados Fundamentalistas',
 '15.01.01.02 - Aluguéis por Remuneração de Capital de Terceiros - Resultados Fundamentalistas',
 '15.01.02 - Remuneração de Capital Próprio por Remuneração de Capital - Resultados Fundamentalistas',
 '15.01.02.01 - Juros Sobre o Capital Próprio por Remuneração de Capital Próprio - Resultados Fundamentalistas',
 '15.01.02.02 - Dividendos por Remuneração de Capital Próprio - Resultados Fundamentalistas',
 '15.01.02.03 - Lucros Retidos por Remuneração de Capital Próprio - Resultados Fundamentalistas',
 '15.02 - Remuneração de Capital por EBIT - Resultados Fundamentalistas',
 '15.02.01 - Impostos por EBIT - Resultados Fundamentalistas',
 '16.01 - Margem Bruta (Resultado Bruto (Receita Líquida) por Receita Bruto) - Resultados Fundamentalistas',
 '16.02 - Margem Operacional (Receitas Operacionais por Receita Bruta) - Resultados Fundamentalistas',
 '16.02.01 - Força de Vendas (Despesas com Vendas por Despesas Operacionais) - Resultados Fundamentalistas',
 '16.02.02 - Peso Administrativo (Despesas com Administração por Despesas Operacionais) - Resultados Fundamentalistas',
 '16.03 - Margem EBITDA (EBITDA por Resultado Bruto (Receita Líquida)) - Resultados Fundamentalistas',
 '16.03.01 - Margem EBIT (EBIT por Resultado Bruto (Receita Líquida)) - Resultados Fundamentalistas',
 '16.03.02 - Margem de Depreciação por Resultado Bruto (Receita Líquida) - Resultados Fundamentalistas',
 '16.04 - Margem Não Operacional (Resultado Não Operacional por Resultado Bruto (Receita Líquida)) - Resultados Fundamentalistas',
 '16.05 - Margem Líquida (Lucro Líquido por Receita Bruta) - Resultados Fundamentalistas',
 '17.01 - Caixa Total - Análise do Fluxo de Caixa',
 '17.02 - Caixa Livre - Análise do Fluxo de Caixa',
 '17.03.01 - Caixa de Investimentos por Caixa das Operações - Análise do Fluxo de Caixa',
 '17.03.02 - Caixa de Investimentos por EBIT - Análise do Fluxo de Caixa',
 '17.04 - Caixa Imobilizado - Análise do Fluxo de Caixa',
 '17.05 - FCFF simplificado (Caixa Livre para a Firma) - Análise do Fluxo de Caixa',
 '17.06 - FCFE simplificado (Caixa Livre para os Acionistas) - Análise do Fluxo de Caixa',
 '18.01 - Margem de Vendas por Valor Agregado - Análise do Valor Agregado',
 '18.02 - Custo dos Insumos por Valor Agregado - Análise do Valor Agregado',
 '18.03 - Valor Adicionado Bruto por Valor Agregado - Análise do Valor Agregado',
 '18.04 - Retenções por Valor Agregado - Análise do Valor Agregado',
 '18.05 - Valor Adicionado Líquido por Valor Agregado - Análise do Valor Agregado',
 '18.06 - Valor Adicionado em Transferência por Valor Agregado - Análise do Valor Agregado',
 '18.07 - Recursos Humanos por Valor Agregado - Análise do Valor Agregado',
 '18.07.01 - Remuneração Direta (Recursos Humanos) por Valor Agregado - Análise do Valor Agregado',
 '18.07.02 - Benefícios (Recursos Humanos) por Valor Agregado - Análise do Valor Agregado',
 '18.07.03 - FGTS (Recursos Humanos) por Valor Agregado - Análise do Valor Agregado',
 '18.08 - Impostos por Valor Agregado - Análise do Valor Agregado',
 '18.09 - Remuneração de Capital de Terceiros por Valor Agregado - Análise do Valor Agregado',
 '18.09.01 - Juros Pagos a Terceiros por Valor Agregado - Análise do Valor Agregado',
 '18.09.02 - Aluguéis Pagos a Terceiros por Valor Agregado - Análise do Valor Agregado',
 '18.10 - Remuneração de Capital Próprio por Valor Agregado - Análise do Valor Agregado',
 '18.10.01 - Juros Sobre Capital Próprio por Valor Agregado - Análise do Valor Agregado',
 '18.10.02 - Dividendos por Valor Agregado - Análise do Valor Agregado',
 '18.10.02 - Lucros Retidos por Valor Agregado - Análise do Valor Agregado',
 '18.11.01 - Alíquota de Impostos (Impostos, Taxas e Contribuições por Receita Bruta) - Análise do Valor Agregado',
 '18.11.02 - Taxa de Juros Pagos (Remuneração de Capital de Terceiros por Receita Bruta - Análise do Valor Agregado',
 '18.11.03 - Taxa de Proventos Gerados (Remuneração de Capital Próprio por Receita Bruta - Análise do Valor Agregado',
 'pregao',
 'company_name',
 'cvm',
 'listagem',
 'ticker',
 'tickers',
 'asin',
 'cnpj',
 'site',
 'setor',
 'subsetor',
 'segmento',
 'atividade',
 'escriturador',
 'url'
]
